# Generated by Django 4.1.7 on 2023-04-03 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_product_category_for_products_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
    ]
