# Generated by Django 4.1.7 on 2023-04-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_price_order_delivery_price_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=8, null=True, verbose_name='цена заказа'),
        ),
    ]
